spring:
    output:
        ansi:
            enabled: always
    application:
        name: lectureenroll
    datasource:
        url: jdbc:h2:mem:test
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            jakarta.persistence.lock.timeout: 10000  # 10초
            hibernate:
                show_sql: true
                lock.timeout: 10000  # 10초
logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.orm.jdbc.bind: debug
